### ISSUE TITLE
Filter errors before logging them

### ISSUE THREAD

**Issue by gzurbach** [jherdman/ember-cli-trackjs#4]
Hello there!

I've been using your lib in production for a week now and it's been working very well. My only issue at the moment is that I'm logging too many things. For instance, ember has a known issue for a while throwing a 'TransitionAborted' error quite often. It represents about 50% of my logs in Track.js this week! 

So my question is: do you think we could add an optional 'hook' in your library to filter errors? This hook would be called in the `configure-trackjs.js` initializer, it would receive the error as a parameter and we could return `true` or `false` depending if we want to log a given error. WDYT?

I am willing to send a PR if you think it makes sense.

Thanks!

**Comment by jherdman** [comment]
I think you may want to check out the [`onError` hook](http://docs.trackjs.com/Examples/Modifying_Errors) TrackJS provides. Will that option work for you?

You'll probably have to work around #3 right now. Hopefully we'll have this fixed soon!

**Comment by gzurbach** [comment]
That makes sense. I will try that today and look after your next release. Thanks for your quick answer I appreciate!

**Comment by jherdman** [comment]
Apologies for the delay in resolving this. If you have a chance this weekend, would you mind looking over #9? I'm circling a solution, but it's unfortunately going to be a breaking change. I'm hoping to get some feedback as I test out my solution.

**Comment by gzurbach** [comment]
I'd love to help. I should have some time tomorrow to try out that stuff. I'm doing a talk in Seattle on the 29th about error monitoring in Ember and I'd like to demo your addon. So let's make it great by then!

**Comment by jherdman** [comment]
Closing. Please see #18.
