### ISSUE TITLE
Uncaught TypeError: app[initializerType] is not a function

### ISSUE THREAD

**Issue by pareshnawale** [jherdman/ember-cli-trackjs#49]
Getting "Uncaught TypeError: app[initializerType] is not a function" error in "ember-load-initializers.js" file.
I am using following versions
Ember: 0.2.7
node: 0.12.7
npm: 2.11.0

I tried adding initializer mentioned "https://github.com/jherdman/ember-cli-trackjs#one-caveat" section but no luck.

Thanks,
Paresh

**Comment by jherdman** [comment]
Which version of ember-cli-trackjs are you using?

**Comment by pareshnawale** [comment]
I am using 1.0.1  version of ember-cli-trackjs.

Thanks,
Paresh

*Paresh Nawale* . Web Application Developer
1140 NW Third Avenue, Canby, OR 97013, USA
Office: 503.263.9100

ScreamingCircuits.com

**Comment by jherdman** [comment]
If you are indeed using Ember 0.2.7, you'll have to downgrade your copy of ember-cli-trackjs to 0.1.6.

**Comment by pareshnawale** [comment]
Hi James,

Thanks for your quick reply. I am still getting same error with version 0.1.6.
Just to clarify here are the versions I am using

Ember CLI: 0.2.7
**Ember: 1.11.1**
node: 0.12.7
npm: 2.11.0

Based on above information do you think I need to try any other version of ember-cli-trackjs?

Thanks,
Paresh

**Comment by jherdman** [comment]
Yeah, maybe try 0.1.5 —hopefully that'll work.

**Comment by pareshnawale** [comment]
Thanks James. Version 0.1.5 did the trick.

-Paresh
