### ISSUE TITLE
Support TrackJS Custom Metadata

### ISSUE THREAD

**Issue by jtferns** [jherdman/ember-cli-trackjs#50]
TrackJS just added support for custom metadata tracking in version [`2.2.0`](https://github.com/TrackJs/trackjs-package/releases/tag/2.2.0):
- [`trackJs.addMetadata(key, value)`](http://docs.trackjs.com/tracker/top-level-api#trackjsaddmetadatakey-value)
- [`trackJs.removeMetadata(key)`](http://docs.trackjs.com/tracker/top-level-api#trackjsremovemetadatakey)

Can the TrackJS service expose these metadata functions?

**Comment by jherdman** [comment]
Absolutely! Are you interested in opening a pull request to expose this API?

**Comment by jtferns** [comment]
:ok_hand:, will PR it in soon.
