### ISSUE TITLE
Request for new release 

### ISSUE THREAD

**Issue by JoseWebby** [jherdman/ember-cli-trackjs#91]
Hi @jherdman,

It seems like there are 13 commits into master after the last/latest release `2.1.0`. I need some latest changes from `master`. So can we have a new release with the latest master please. 
Thanks in advance!

**Comment by jherdman** [comment]
Absolutely. I'll try to whip something up today.

**Comment by JoseLawrence** [comment]
Cool, thanks @jherdman

**Comment by jherdman** [comment]
@JoseLawrence I'm working on the release still (life, etc.). Do you have time to try #93 in your app to see if it works for you? I wanted to resolve this and #72 before releasing if possible.

**Comment by JoseWebby** [comment]
@jherdman - Sure I will check and get back to you on this. Thanks!

**Comment by jherdman** [comment]
Done!

https://github.com/jherdman/ember-cli-trackjs/releases/tag/3.0.0

**Comment by JoseWebby** [comment]
@jherdman Thanks!
